### ISSUE TITLE
AJAJAJAJAJJAJAJAJA

### ISSUE THREAD

**Issue by Danilop95** [DanNduati/Jokes_api#11]
JAJAJAJAJJAJAJAJAJAJJAA

**Comment by zalaya** [comment]
JSADJSDAJFASDJGASDJASDGJASGDJASDGJASDG

**Comment by Danilop95** [comment]
JAJAJa aJAJAJAJ JAJA a a JAJAJAJ jjj aj ajaj JAJ AJAJ
